influxdb:
  bucket: ***REMOVED***
  org: "***REMOVED***"
  token: ***REMOVED***
  url: "***REMOVED***/"
  verify_ssl: false
  timeout: 900000


Location:
  proj: "utm"
  zone: 30
  ellps: "WGS84"
  south: false
  code: "epsg:4326"
  zoneInfo: "Europe/Madrid"


Display:
  mode: "Screen"


tags:
  ref_tag: "CodeID"
  foot_tag: "Foot"


spectrogram:
  window_s: 10.0
  delta_t_s: 1.0
  fmax_hz: 5.0
  window_type: "hann"
  power_scale: "db"

  signals:
    - "Ax"
    - "Gx"
    - "S2"

  feet:
    - "Right"
    - "Left"

  resample_hz: 100.0