[tool.poetry]
name = "gait-analysis-tfg"
version = "0.1.0"
description = "Extraccion y procesado espectral de señales de marcha desde InfluxDB"
authors = ["Clarissa <c.otanez@alumnos.upm.es>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
influxdb-client = "^1.48.0"
PyYAML = "^6.0.2"
numpy = "^2.1"
pandas = "^2.2.3"
scipy = "^1.14.0"
pyarrow = "^17.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"